# Generated by Django 5.0.6 on 2024-06-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_create", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("price", models.CharField(max_length=200, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("Indoor", "Indoor"), ("Out Door", "Out Door")],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("date_create", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
