# Generated by Django 5.0.6 on 2024-06-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Indoor", "Indoor"),
                    ("Out Door", "Out Door"),
                    ("chops", "chops"),
                    ("Food", "Food"),
                    ("Snacks", "Snacks"),
                    ("appetizer", "appetizer"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
