# Generated by Django 5.0.6 on 2024-07-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="nates",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
