# Generated by Django 5.0.6 on 2024-07-15 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_rename_name_customer_first_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="date_created",
            new_name="date_create",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="last_name",
        ),
    ]
