# Generated by Django 5.0.6 on 2026-06-17 15:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_drop_product_category_old_tmp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_create']},
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_inventory',
            field=models.BooleanField(default=False, help_text='Manage ingredients and stock levels'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_payments',
            field=models.BooleanField(default=False, help_text='Confirm and manage order payments'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(help_text='e.g. CREATE, UPDATE, DELETE', max_length=50),
        ),
        migrations.AlterField(
            model_name='branchproduct',
            name='quantity_available',
            field=models.PositiveIntegerField(default=0, help_text='Current stock count'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Null = valid at all branches', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(default=1, help_text='Max total uses, 0 = unlimited'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user_avatar.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='label',
            field=models.CharField(blank=True, help_text='e.g. Home, Office', max_length=100),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='proof_of_delivery',
            field=models.ImageField(blank=True, help_text='Photo confirmation of delivery', null=True, upload_to='deliveries/'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='reorder_level',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Alert when stock falls below this', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(help_text='e.g. kg, litres, pieces', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–15 digits, optional leading +).', regex='^\\+?1?\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Awaiting Payment', 'Awaiting Payment'), ('Paid', 'Paid'), ('Preparing', 'Preparing'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], db_index=True, default='Awaiting Payment', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price (N). BranchProduct can override per branch.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='accounts.tag'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='1–5 stars', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_manage_products',
            field=models.BooleanField(default=False, help_text='Add and edit products (legacy — use granular flags above)'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='accounts.country'),
        ),
    ]
