# Generated by Django 5.0.6 on 2026-06-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_make_auth_user_email_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
    ]
