# Generated by Django 5.0.6 on 2026-06-20 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_order_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_confirmed',
            field=models.BooleanField(default=False, help_text='Has the customer confirmed receiving the order?'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatcher_confirmed',
            field=models.BooleanField(default=False, help_text='Has the dispatcher confirmed delivery?'),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatcher_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatcher_confirmed_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who confirmed delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_by',
            field=models.CharField(blank=True, help_text='Who confirmed/processed the payment', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Additional notes for offline payments'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Bank transfer reference or transaction ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Confirmed', 'Confirmed'), ('Preparing', 'Preparing'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', help_text='Physical fulfillment status of the order', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Bank Transfer', 'Bank Transfer'), ('Card', 'Debit/Credit Card'), ('Mobile Money', 'Mobile Money')], default='Cash on Delivery', help_text='How the customer will pay', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Payment'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', help_text='Payment collection status', max_length=30),
        ),
        migrations.CreateModel(
            name='IngredientConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=3, max_digits=10)),
                ('consumed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('consumed_by', models.ForeignKey(blank=True, help_text='Staff who marked order as preparing', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='accounts.ingredient')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_consumptions', to='accounts.order')),
            ],
            options={
                'verbose_name': 'Ingredient Consumption',
                'verbose_name_plural': 'Ingredient Consumptions',
                'ordering': ['-consumed_at'],
            },
        ),
    ]
