# Generated by Django 5.0.6 on 2026-06-20 07:48

from django.db import migrations


def migrate_order_and_payment_status(apps, schema_editor):
    """
    Convert old order/payment status to new separated system:
    - Old "Awaiting Payment" → New "Pending" (order) + "Pending" (payment)
    - Old "Paid" → New "Confirmed" (order) + "Paid" (payment)
    - Update payment methods: "Transfer" → "Bank Transfer", "Cash" → "Cash on Delivery"
    """
    Order = apps.get_model('accounts', 'Order')
    Payment = apps.get_model('accounts', 'Payment')
    
    # Migrate orders with "Awaiting Payment" status
    awaiting_orders = Order.objects.filter(status='Awaiting Payment')
    for order in awaiting_orders:
        order.status = 'Pending'
        order.save(update_fields=['status'])
        # Payment status already defaults to 'Pending'
    
    print(f'Migrated {awaiting_orders.count()} "Awaiting Payment" orders to "Pending"')
    
    # Migrate orders with "Paid" status
    paid_orders = Order.objects.filter(status='Paid')
    for order in paid_orders:
        order.status = 'Confirmed'
        order.save(update_fields=['status'])
        
        # Update corresponding payment to "Paid"
        try:
            payment = order.payment
            if payment.status == 'Pending':
                payment.status = 'Paid'
                payment.save(update_fields=['status'])
        except Payment.DoesNotExist:
            pass
    
    print(f'Migrated {paid_orders.count()} "Paid" orders to "Confirmed"')
    
    # Update payment methods to new format
    Payment.objects.filter(method='Transfer').update(method='Bank Transfer')
    Payment.objects.filter(method='Cash').update(method='Cash on Delivery')
    Payment.objects.filter(method='USSD').update(method='Mobile Money')
    
    print('Updated payment method names')


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration if needed:
    - "Pending" → "Awaiting Payment"
    - "Confirmed" → "Paid"
    """
    Order = apps.get_model('accounts', 'Order')
    Payment = apps.get_model('accounts', 'Payment')
    
    Order.objects.filter(status='Pending').update(status='Awaiting Payment')
    Order.objects.filter(status='Confirmed').update(status='Paid')
    
    # Reverse payment method names
    Payment.objects.filter(method='Bank Transfer').update(method='Transfer')
    Payment.objects.filter(method='Cash on Delivery').update(method='Cash')
    Payment.objects.filter(method='Mobile Money').update(method='USSD')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_order_customer_confirmed_order_customer_confirmed_at_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_order_and_payment_status, reverse_migration),
    ]
