# Generated by Django 5.0.6 on 2026-06-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_migrate_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_confirm_delivery',
            field=models.BooleanField(default=False, help_text='Confirm delivery of orders (dispatcher role)'),
        ),
    ]
