# Generated by Django 5.0.6 on 2026-06-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_add_can_confirm_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_assign_dispatcher',
            field=models.BooleanField(default=False, help_text='Assign a dispatcher to an order'),
        ),
    ]
