# Generated by Django 5.0.6 on 2026-06-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_add_can_assign_dispatcher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment'},
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_reference__gt', '')), fields=('payment_reference',), name='unique_nonempty_payment_reference'),
        ),
    ]
