# Generated by Django 5.1.1 on 2024-10-04 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customer_profile_pic_alter_customer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info_extend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('whatsappNumber', models.BigIntegerField(blank=True, null=True)),
                ('user_type', models.CharField(default='sub_admin', max_length=20)),
                ('username', models.CharField(default='', max_length=100, unique=True, verbose_name='Username')),
                ('photo', models.ImageField(blank=True, default='/static/images/profile1.png', null=True, upload_to='users')),
                ('country', models.CharField(default='Nigeria', max_length=200, null=True)),
                ('verification_status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
