# Generated by Django 5.1.1 on 2024-10-04 16:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_info_extend_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_info_extend',
            new_name='UserInfoExtend',
        ),
    ]
