# Generated by Django 5.1.1 on 2024-10-04 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rename_user_info_extend_userinfoextend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_zone', models.CharField(blank=True, max_length=128, null=True, verbose_name='Zone')),
                ('location_city', models.CharField(blank=True, max_length=128, null=True, verbose_name='City')),
                ('location_town', models.CharField(max_length=128, verbose_name='Town')),
                ('location_state', models.CharField(default='Lagos', max_length=64, verbose_name='State')),
                ('location_country', models.CharField(default='Nigeria', max_length=64, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('apart', models.CharField(blank=True, max_length=128, null=True, verbose_name='Apartment')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='City')),
                ('town', models.CharField(max_length=128, verbose_name='Town')),
                ('state', models.CharField(default='Lagos', max_length=64, verbose_name='State')),
                ('country', models.CharField(default='Nigeria', max_length=64, verbose_name='Country')),
                ('bike_number', models.CharField(blank=True, max_length=10, null=True)),
                ('bike_insurance', models.CharField(blank=True, max_length=100, null=True)),
                ('bike_traking', models.CharField(blank=True, max_length=30, null=True)),
                ('user_type', models.CharField(default='rider', max_length=20)),
                ('Guarantor_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Guarantor_mobile_number', models.CharField(blank=True, max_length=30, null=True)),
                ('Guarantor_address', models.CharField(max_length=50)),
                ('Guarantor_apart', models.CharField(blank=True, max_length=128, null=True, verbose_name='Apartment')),
                ('Guarantor_city', models.CharField(blank=True, max_length=128, null=True, verbose_name='City')),
                ('Guarantor_town', models.CharField(blank=True, max_length=128, null=True, verbose_name='Town')),
                ('Guarantor_state', models.CharField(default='Lagos', max_length=64, verbose_name='State')),
                ('valid_id', models.BinaryField(blank=True, max_length=20, null=True)),
                ('user_image', models.ImageField(default='default.jpg', upload_to='')),
                ('highest_level_of_education', models.CharField(blank=True, max_length=20, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_date', models.DateField(auto_now=True)),
                ('assignedTasks', models.IntegerField(default=0)),
                ('completedTasks', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nates',
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(default='none', max_length=420, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_apart',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Apartment'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_city',
            field=models.CharField(default='none', max_length=128, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_country',
            field=models.CharField(default='Nigeria', max_length=64, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_email',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_no',
            field=models.CharField(db_index=True, default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_state',
            field=models.CharField(default='Lagos', max_length=64, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_town',
            field=models.CharField(default='none', max_length=128, verbose_name='Town'),
        ),
        migrations.AddField(
            model_name='customer',
            name='dt_reg',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.CharField(default='Mafoluku', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deliver_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, default='Same-Day Delivery', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='pck_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pck_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pricing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reference_number',
            field=models.CharField(default='none', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderC', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('bank', models.CharField(default=None, max_length=20)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
            options={
                'ordering': ('-order_date',),
            },
        ),
        migrations.CreateModel(
            name='Receipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_email', models.EmailField(max_length=100)),
                ('receiver_phone', models.BigIntegerField()),
                ('receiver_address', models.CharField(max_length=100)),
                ('receiver_apart', models.CharField(blank=True, max_length=128, null=True, verbose_name='Apartment')),
                ('receiver_city', models.CharField(blank=True, max_length=128, null=True, verbose_name='City')),
                ('receiver_town', models.CharField(max_length=128, verbose_name='Town')),
                ('receiver_state', models.CharField(default='Lagos', max_length=64, verbose_name='State')),
                ('receiver_country', models.CharField(default='Nigeria', max_length=64, verbose_name='Country')),
                ('dt_reg', models.DateTimeField(auto_now=True, verbose_name='')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='receipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.receipient'),
        ),
        migrations.AddField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.rider'),
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('receipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.receipient')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
